/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    AudioResultPanel: typeof import('./src/components/AudioResultPanel.vue')['default']
    BatchParameterPanel: typeof import('./src/components/workspace/BatchParameterPanel.vue')['default']
    DirtySegmentBadge: typeof import('./src/components/workspace/DirtySegmentBadge.vue')['default']
    EdgeParameterPanel: typeof import('./src/components/workspace/EdgeParameterPanel.vue')['default']
    EndSessionDialog: typeof import('./src/components/workspace/EndSessionDialog.vue')['default']
    ExportDialog: typeof import('./src/components/workspace/ExportDialog.vue')['default']
    FileImportZone: typeof import('./src/components/text-input/FileImportZone.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    InferenceControlBar: typeof import('./src/components/InferenceControlBar.vue')['default']
    InferenceSettingsPanel: typeof import('./src/components/InferenceSettingsPanel.vue')['default']
    MainActionButton: typeof import('./src/components/workspace/MainActionButton.vue')['default']
    ParameterDraftBar: typeof import('./src/components/workspace/ParameterDraftBar.vue')['default']
    ParameterDraftConfirm: typeof import('./src/components/workspace/ParameterDraftConfirm.vue')['default']
    ParameterPanelHost: typeof import('./src/components/workspace/ParameterPanelHost.vue')['default']
    ParameterSlider: typeof import('./src/components/ParameterSlider.vue')['default']
    PauseBoundaryNodeView: typeof import('./src/components/workspace/workspace-editor/PauseBoundaryNodeView.vue')['default']
    RenderJobProgressBar: typeof import('./src/components/workspace/RenderJobProgressBar.vue')['default']
    ResetSessionDialog: typeof import('./src/components/workspace/ResetSessionDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuntimeInferenceSettingsPanel: typeof import('./src/components/workspace/parameter-panel/RuntimeInferenceSettingsPanel.vue')['default']
    SegmentBlockNodeView: typeof import('./src/components/workspace/workspace-editor/list/SegmentBlockNodeView.vue')['default']
    SegmentListDisplay: typeof import('./src/components/workspace/SegmentListDisplay.vue')['default']
    SegmentParameterPanel: typeof import('./src/components/workspace/SegmentParameterPanel.vue')['default']
    SegmentPreviewList: typeof import('./src/components/text-input/SegmentPreviewList.vue')['default']
    SendToWorkspaceBar: typeof import('./src/components/text-input/SendToWorkspaceBar.vue')['default']
    SessionParameterPanel: typeof import('./src/components/workspace/SessionParameterPanel.vue')['default']
    SharedParameterScopePanel: typeof import('./src/components/workspace/parameter-panel/SharedParameterScopePanel.vue')['default']
    StatusIndicator: typeof import('./src/components/StatusIndicator.vue')['default']
    TextInputArea: typeof import('./src/components/text-input/TextInputArea.vue')['default']
    TransportControlBar: typeof import('./src/components/workspace/TransportControlBar.vue')['default']
    TtsForm: typeof import('./src/components/TtsForm.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UEditor: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Editor.vue')['default']
    VoiceSelect: typeof import('./src/components/VoiceSelect.vue')['default']
    WaveformStrip: typeof import('./src/components/workspace/WaveformStrip.vue')['default']
    WorkspaceEditorHost: typeof import('./src/components/workspace/WorkspaceEditorHost.vue')['default']
    WorkspaceEmptyState: typeof import('./src/components/workspace/WorkspaceEmptyState.vue')['default']
    WorkspaceFailedState: typeof import('./src/components/workspace/WorkspaceFailedState.vue')['default']
    WorkspaceInitForm: typeof import('./src/components/workspace/WorkspaceInitForm.vue')['default']
    WorkspaceInitProgress: typeof import('./src/components/workspace/WorkspaceInitProgress.vue')['default']
  }
}
